### ISSUE TITLE
Change Language to UK English?

### ISSUE THREAD

**Issue by SparkieDEV2** [wiesty/MMM-CoupleDays#1]
Hi mate, is there a way to change the language to UK English by any chance? I want to use this module to track the age of my kids...

**Comment by wiesty** [comment]
> Hi mate, is there a way to change the language to UK English by any chance? I want to use this module to track the age of my kids...

Will add that! 
Also there is a small bug rn. Eta 2 weeks?👍 will reply then

**Comment by wiesty** [comment]
Hi @SparkieDEV2 ,

kindly reclone the module. Add the lang variable to your config and you are all set. The Module was not meant to be for birthdays but you can still add multiple instances to your config so you can track them (see the config tempalte for single name options) 

Greetings


Closing this issue with commit [1488aea14ed1293ea2ca9942e56b380b0bf49a15](https://github.com/wiesty/MMM-CoupleDays/commit/9f1de21c9cac8a051bd3ed15666dca4fd0384739)
