### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by wedding0371** [wiesty/MMM-CoupleDays#4]
**Hi wiesty:**

Thank you for this awesome module. 
I made a chinese simple translation for project, maybe can help 😊

**usage:**
` language: "zh-cn" `

**the file <zh-cn.json>:**
```
{
    "day": "天",
    "days": "天",
    "week": "周",
    "weeks": "周",
    "month": "月",
    "months": "月",
    "year": "年",
    "years": "年",
    "total": "共计",
    "and": "与",
    "years_plural": "年时光" 
}
```

**Comment by wiesty** [comment]
Nice work. Added 👍🏻 

Feel free to create a merge request next time on other projects 💯 

 Thank you!
