### ISSUE TITLE
Translation nl

### ISSUE THREAD

**Issue by Koesie77** [wiesty/MMM-CoupleDays#6]
Sorry am new to Github, no idea how to get you the file anoy other way 
Made a Dutch translation for MMM-Coupledays.
Greetings from a fellow Münchener living in NL 
[nl.json](https://github.com/wiesty/MMM-CoupleDays/files/13205398/nl.json)

**Comment by wiesty** [comment]
Thank you! Will add that. 👌👍

**Comment by wiesty** [comment]
added :)
